### ISSUE TITLE
missing features from the list in the readme

### ISSUE THREAD

**Issue by UltraBlackLinux** [Exortions/skyblock-2.0#27]
According to the readme, slayer quests and mobs are already a thing, though I can't find any on the map. Why is that?

Also, merchants are mentioned - I would thus expect, that they fully work, but none are selling items and the item selling feature does not work with any of them.

Also isn't the bazaar already implemented?

**Comment by Exortions** [comment]
No the bazaar isn't implemented.

The merchants are implemented (no buying multiples or selling), only the Miner Merchant has items though. You can edit the items if you go into `<plugins folder>/Skyblock/merchants.json`

Slayers are implemented by @OptimusChen, do /sb batphone. (they might be broken because we just added some recent changes to how coins are handled though)

**Comment by UltraBlackLinux** [comment]
You got discord or matrix or something like that? I don't wanna open an issue for everything that I come across that might not even be worth one

**Comment by Exortions** [comment]
Yeah, Exortions#8077
